### ISSUE TITLE
react warning :  React does not recognize the `splitDirection` prop on a DOM element

### ISSUE THREAD

**Issue by mejjjor** [YannickBochatay/react-desktop-panels#11]
## Reproduction
Utiliser un composant Panel avec une propriété  splitDirection setté.

## Comportement observé 
Il y a un warning dans la console :
![image](https://user-images.githubusercontent.com/6237350/224301113-22abd92b-2679-4ada-89c0-da23635aaa2e.png)

## Comportement attendu
Ne plus avoir de warning

**Comment by YannickBochatay** [comment]
Corrigé en version 1.2.3 : https://github.com/YannickBochatay/react-desktop-panels/commit/caae3f328a9b1955dd87c1f0908d6cde39f73125
